// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.
// Auto-generated from Rust backend types using ts-rs

export const MCP_SUPPORTED_EXECUTORS: string[] = [
    "claude",
    "amp",
    "gemini",
    "sst-opencode",
    "charm-opencode",
    "claude-code-router"
];
