// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Auto-generated from Rust backend types using ts-rs

export type ApiResponse<T> = { success: boolean, data: T | null, message: string | null, };

export type Config = { theme: ThemeMode, executor: ExecutorConfig, disclaimer_acknowledged: boolean, sound_alerts: boolean, };

export type ThemeMode = "light" | "dark" | "system";

export type ExecutorConfig = { "type": "echo" } | { "type": "claude" } | { "type": "amp" };

export type CreateProject = { name: string, git_repo_path: string, use_existing_repo: boolean, setup_script: string | null, };

export type Project = { id: string, name: string, git_repo_path: string, setup_script: string | null, created_at: Date, updated_at: Date, };

export type UpdateProject = { name: string | null, git_repo_path: string | null, setup_script: string | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type CreateTask = { project_id: string, title: string, description: string | null, };

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type Task = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, created_at: string, updated_at: string, };

export type TaskWithAttemptStatus = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, created_at: string, updated_at: string, has_in_progress_attempt: boolean, };

export type UpdateTask = { title: string | null, description: string | null, status: TaskStatus | null, };

export type TaskAttemptStatus = "init" | "setuprunning" | "setupcomplete" | "setupfailed" | "executorrunning" | "executorcomplete" | "executorfailed" | "paused";

export type TaskAttempt = { id: string, task_id: string, worktree_path: string, merge_commit: string | null, executor: string | null, stdout: string | null, stderr: string | null, created_at: string, updated_at: string, };

export type CreateTaskAttempt = { task_id: string, worktree_path: string, merge_commit: string | null, executor: string | null, };

export type UpdateTaskAttempt = { worktree_path: string | null, merge_commit: string | null, };

export type TaskAttemptActivity = { id: string, task_attempt_id: string, status: TaskAttemptStatus, note: string | null, created_at: string, };

export type CreateTaskAttemptActivity = { task_attempt_id: string, status: TaskAttemptStatus | null, note: string | null, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, };

export type DiffChunkType = "Equal" | "Insert" | "Delete";

export type DiffChunk = { chunk_type: DiffChunkType, content: string, };

export type FileDiff = { path: string, chunks: Array<DiffChunk>, };

export type WorktreeDiff = { files: Array<FileDiff>, };

export type BranchStatus = { is_behind: boolean, commits_behind: number, commits_ahead: number, up_to_date: boolean, merged: boolean, };