// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Auto-generated from Rust backend types using ts-rs

type ApiResponse<T> = { success: boolean, data: T | null, message: string | null, };

type CreateProject = { name: string, };

type CreateUser = { email: string, password: string, is_admin: boolean | null, };

type LoginRequest = { email: string, password: string, };

type LoginResponse = { user: User, token: string, };

type Project = { id: string, name: string, owner_id: string, created_at: Date, updated_at: Date, };

type UpdateProject = { name: string | null, };

type UpdateUser = { email: string | null, password: string | null, is_admin: boolean | null, };

type User = { id: string, email: string, is_admin: boolean, created_at: Date, updated_at: Date, };
